language: node_js
node_js:
 - "8"
 - "10"
 - "node"
script:
  - npm run build
  - npm run lint
  - npm test
  - npm browser
after_success:
  - npm run coveralls
cache:
  directories:
    - node_modules
